### ISSUE TITLE
Cannot read properties of undefined (reading 'split') when calling generateOpenApiSpec

### ISSUE THREAD

**Issue by GorgeousPuree** [omermecitoglu/next-openapi-json-generator#18]
```
import generateOpenApiSpec from "@omer-x/next-openapi-json-generator";
import ReactSwagger from "@/components/ReactSwagger";
import { LicenceDTO } from "@/lib/models/license";

const Page = async () => {
  const spec = await generateOpenApiSpec({
    LicenceDTO,
  });
  return <ReactSwagger spec={spec} />;
};

export default Page;

```

Console output:
```
next dev --turbo
  ▲ Next.js 15.0.0-rc.1 (turbo)
  - Local:        http://localhost:3000
  - Environments: .env

 ✓ Starting...
 ✓ Compiled in 595ms
 ✓ Ready in 2s
 ○ Compiling /swagger ...
 ✓ Compiled /swagger in 5.3s
 ⨯ TypeError: Cannot read properties of undefined (reading 'split')
    at getModuleName (C:\Users\Petya\WebstormProjects\aaa-nextjs4\aaa-nextjs\.next\server\chunks\ssr\node_modules_b3a5ac._.js:25:24)
    at getPackageMetadata (C:\Users\Petya\WebstormProjects\aaa-nextjs4\aaa-nextjs\.next\server\chunks\ssr\node_modules_b3a5ac._.js:32:24)
    at generateOpenApiSpec (C:\Users\Petya\WebstormProjects\aaa-nextjs4\aaa-nextjs\.next\server\chunks\ssr\node_modules_b3a5ac._.js:8664:201)
    at async Page (C:\Users\Petya\WebstormProjects\aaa-nextjs4\aaa-nextjs\.next\server\chunks\ssr\[root of the server]__8d7b59._.js:143:18)
digest: "260999674"
 GET /swagger 500 in 5723ms
```

package.json:
```
{
  "private": true,
  "scripts": {
    "dev": "next dev --turbo",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "@omer-x/next-openapi-json-generator": "^1.2.1",
    "@omer-x/next-openapi-route-handler": "^1.6.0",
    "@radix-ui/react-dialog": "^1.1.1",
    "@radix-ui/react-dropdown-menu": "^2.1.1",
    "@radix-ui/react-slot": "^1.1.0",
    "@radix-ui/react-tabs": "^1.1.0",
    "@radix-ui/react-tooltip": "^1.1.2",
    "@types/node": "22.7.5",
    "@types/react": "^18.3.12",
    "@types/react-dom": "^18.3.1",
    "@vercel/analytics": "^1.3.1",
    "autoprefixer": "^10.4.19",
    "class-variance-authority": "^0.7.0",
    "clsx": "^2.1.1",
    "drizzle-kit": "^0.28.0",
    "drizzle-orm": "0.36.1",
    "drizzle-zod": "^0.5.1",
    "lucide-react": "^0.400.0",
    "next": "15.0.0-rc.1",
    "next-auth": "5.0.0-beta.19",
    "pg": "^8.13.1",
    "postcss": "^8.4.39",
    "prettier": "^3.3.2",
    "prop-types": "^15.8.1",
    "react": "19.0.0-rc-cd22717c-20241013",
    "react-dom": "19.0.0-rc-cd22717c-20241013",
    "server-only": "^0.0.1",
    "swagger-ui-react": "^5.18.2",
    "tailwind-merge": "^2.3.0",
    "tailwindcss": "^3.4.4",
    "tailwindcss-animate": "^1.0.7",
    "zod": "^3.23.8"
  },
  "prettier": {
    "arrowParens": "always",
    "singleQuote": true,
    "tabWidth": 2,
    "trailingComma": "none"
  },
  "pnpm": {
    "overrides": {
      "@types/react": "npm:types-react@19.0.0-rc.1",
      "@types/react-dom": "npm:types-react-dom@19.0.0-rc.1"
    }
  },
  "devDependencies": {
    "@omer-x/next-openapi-interface-generator": "^0.11.0",
    "@omer-x/next-openapi-scaffold-generator": "^0.3.0",
    "@omer-x/openapi-types": "^0.2.1",
    "@types/pg": "^8.11.10",
    "@types/swagger-ui-react": "^4.18.3",
    "tsx": "^4.19.2",
    "typescript": "5.6.3"
  }
}
```
Any ideas what causes error in the log? Should be some packages versions incompatibility? Running on Windows using Node v22.11.0

**Comment by omermecitoglu** [comment]
Oh it's because you don't have a package name in your `package.json` but I'll fix it though
