### ISSUE TITLE
 This is not a Next.js application Error when app is deployed on Vercel

### ISSUE THREAD

**Issue by GorgeousPuree** [omermecitoglu/next-openapi-json-generator#29]
```
Error: This is not a Next.js application!
    at generateOpenApiSpec (/var/task/.next/server/chunks/764.js:638:31)
    at async /var/task/.next/server/app/swagger/page.js:57417:21
```

Here's the error I get, when I try to open a swagger **page** that uses `generateOpenApiSpec`. When I build and run my app locally, it works fine. When app is deployed on Vercel, I get this error.
As I said error arrises when calling `generateOpenApiSpec` from the **page**, from the route it works fine. So it must be related to how `process.cwd()` works in Edge runtime.

https://github.com/omermecitoglu/next-openapi-json-generator/blob/main/src/core/next.ts
```
export async function findAppFolderPath() {
  const inSrc = path.resolve(process.cwd(), "src", "app");
  if (await directoryExists(inSrc)) {
    return inSrc;
  }
  const inRoot = path.resolve(process.cwd(), "app");
  if (await directoryExists(inRoot)) {
    return inRoot;
  }
  return null;
}
```

**Comment by GorgeousPuree** [comment]
Hmm, there're not much details... I have the same spec for api route and swagger page. Api route works fine and returns json, but swagger page fails and in Vercel logs I can see Error: `This is not a Next.js application!` in my swagger page route. I think it should be something with `process.cwd()`, but I am not sure...
Using Next 14.1.1

```
import {
  ImageFileDTO,
  NewOrderImageDTO,
  OrderDTO,
  ShortOrderDTO,
  NewOrderDTO,
  UpdatedOrderFieldsDTO,
} from '@/models/entities/order';
import { GetOrdersRequestDTO } from '@/models/requests/getOrdersRequest';
import { PaginationRequestDTO } from '@/models/shared/paginationRequest';
import { GetOrdersResponseDTO } from '@/models/shared/paginationResponse';
import ReactSwagger from '@/ui/components/layout/reactSwagger';
import generateOpenApiSpec from '@omer-x/next-openapi-json-generator';

const Page = async () => {
  console.warn(process.cwd());

  const swaggerSpec = await generateOpenApiSpec(
    {
      ImageFileDTO,
      NewOrderImageDTO,
      GetOrdersResponseDTO,
      PaginationRequestDTO,
      GetOrdersRequestDTO,
      OrderDTO,
      ShortOrderDTO,
      NewOrderDTO,
      UpdatedOrderFieldsDTO,
    },
    {
      securitySchemes: {
        BearerAuth: {
          type: 'http',
          scheme: 'bearer',
        },
      },
      security: [],
    }
  );

  return <ReactSwagger spec={swaggerSpec} />;
};

export default Page;
```

```
'use client';
import SwaggerUI from 'swagger-ui-react';
import 'swagger-ui-react/swagger-ui.css';
import type { OpenApiDocument } from '@omer-x/openapi-types';

type ReactSwaggerProps = {
  spec: OpenApiDocument;
};

const ReactSwagger = ({ spec }: ReactSwaggerProps) => {
  return <SwaggerUI spec={spec} url='/api/swagger' />;
};

export default ReactSwagger;
```


```
import {
  ImageFileDTO,
  NewOrderImageDTO,
  OrderDTO,
  ShortOrderDTO,
  NewOrderDTO,
  UpdatedOrderFieldsDTO,
} from '@/models/entities/order';
import { GetOrdersRequestDTO } from '@/models/requests/getOrdersRequest';
import { PaginationRequestDTO } from '@/models/shared/paginationRequest';
import { GetOrdersResponseDTO } from '@/models/shared/paginationResponse';
import generateOpenApiSpec from '@omer-x/next-openapi-json-generator';

export async function GET() {
  console.warn(process.cwd());

  const swaggerSpec = await generateOpenApiSpec(
    {
      ImageFileDTO,
      NewOrderImageDTO,
      GetOrdersResponseDTO,
      PaginationRequestDTO,
      GetOrdersRequestDTO,
      OrderDTO,
      ShortOrderDTO,
      NewOrderDTO,
      UpdatedOrderFieldsDTO,
    },
    {
      securitySchemes: {
        BearerAuth: {
          type: 'http',
          scheme: 'bearer',
        },
      },
      security: [],
    }
  );

  return Response.json(swaggerSpec);
}
```

**Comment by omermecitoglu** [comment]
![image](https://github.com/user-attachments/assets/6a879d0f-d059-4281-a1b9-a3345cde2744)

In my project, homepage is the swagger docs and it is static as you can see

![image](https://github.com/user-attachments/assets/0b3de5e2-6b4b-412f-801d-b6e8543c1d31)

If it wasn't your intention to build it in runtime, then you should try to find why it's trying to render the page in runtime

Maybe you can try [route-segment-configs](https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config#dynamic) in that page
```typescript
export const dynamic = 'force-static'
```

**Comment by GorgeousPuree** [comment]
OHH, that makes sense. Yes, it works fine with `'force-static'`. Thank you very much, Omer, for such a quick response.

**Comment by omermecitoglu** [comment]
But I suggest you to find why it's switching to dynamic instead of using "force-static"
There might be some unexpected behavior when you force it

**Comment by omermecitoglu** [comment]
https://nextjs.org/docs/app/building-your-application/rendering/server-components#dynamic-rendering

**Comment by GorgeousPuree** [comment]
Thanks, I'll take a deeper look.
